# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  
  config.vm.box = 'ubuntu/xenial64'
  config.vm.hostname = 'openstack1604'

  config.vm.network 'private_network', ip: '192.168.99.100', \
    virtualbox__intnet: true

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '8192'
    vb.cpus = 4
  end

  config.vm.provision 'file', source: '../bootstrap.sh', \
                            destination: '/tmp/bootstrap.sh'
  config.vm.provision "shell",
    run: "always",
    inline: "cd /tmp/ && chmod +x bootstrap.sh && su -c './bootstrap.sh -b stable/queens -l enp0s8' vagrant && cd -"
end
