# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'vagrant-aws'

Vagrant.configure("2") do |config|
  # Set up base box as centos/7. Most be at least version 7
  # to use Docker.
  config.vm.box = "aws"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"      

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['ACCESS_KEY_ID']
    aws.secret_access_key = ENV['SECRET_ACCESS_KEY']
    aws.keypair_name = "SDN"
    aws.instance_type = "t2.micro"
    aws.security_groups = ["launch-wizard-1"]
    aws.region = "eu-west-3"
    aws.tags = {
        'Name' => 'SDN Vagrant instance'
    }

    
    aws.region_config "eu-west-3", :ami => ENV['VM_AMI'] || "ami-bfff49c2"
    aws.block_device_mapping = [{ 'DeviceName' => '/dev/sda1', 'Ebs.VolumeSize' => 15 }]



    override.ssh.username = "centos"
    override.ssh.private_key_path = ENV['SSH_KEY_PATH']
  end
  # Provision with bootstrap.sh
  if !ENV['VM_AMI']
    config.vm.provision :shell, :path => "bootstrap.sh"
  end
end
